### ISSUE TITLE
Make tokenized_validator accept more than one token

### ISSUE THREAD

**Issue by vergeev** [devmanorg/fiasko_bro#5]
We might want to validate a Django challenge but also a Challenge that uses SQLAlchemy or something like that.

**Comment by Melevir** [comment]
What would be final api for the issue? How `tokenized_validator` would look like?

**Comment by Askanio234** [comment]
I was thinking on changing signature to accept a list of tokens, returning wrapper if atleast one is in repo.

**Comment by Melevir** [comment]
Show example, pls.

**Comment by Askanio234** [comment]
Something like that:
``def tokenized_validator(list_of_tokens): // list_of_tokens =['token_a', token_b']
    def validator_decorator(func):
        @functools.wraps(func)
        def func_wrapper(*args, **kwargs):
            repo_tokens = kwargs.get('validator_token')
            if [token for token in list_of_tokens if token in repo_tokens]:
                return func(*args, **kwargs)
        return func_wrapper
    return validator_decorator``

That way you can set tokens in code_validator as either a single string (as is done right now) ```code_validator.validate(solution_repo=solution_repo, validator_token='token_a')``` or as a list of strings ```validator_token = ['token_a', 'token_b']

**Comment by Melevir** [comment]
Nice, do this pls.
