### ISSUE TITLE
Fix pep8 test validator

### ISSUE THREAD

**Issue by Askanio234** [devmanorg/fiasko_bro#52]
https://github.com/devmanorg/fiasko_bro/blob/a8f9b434e332a517bac7470825d099d5fb3a7af0/tests/test_general_validators/test_pep8_violations.py#L14

This test will always pass. We need to get rid of expected_output in the first line and change two last lines to output.

**Comment by patrnk** [comment]
I disagree.

Why do you think that it will always pass?

Here's my argument: when there are not many pep8 violations (less then some critical amount), the validator returns `None`, do there's no problem in a little variation on the number of errors.
