### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by patrnk** [devmanorg/fiasko_bro#6]
Every error group should have its own fixture repo that would be used in tests.

**Comment by Melevir** [comment]
+Travis interration
+ README badge

**Comment by Askanio234** [comment]
I would like to work on this issue

**Comment by Ranc58** [comment]
How about tests for some validators, for example:
```
def has_frozen_requirements(solution_repo, *args, **kwargs):
    requirements = solution_repo.get_file('requirements.txt')
    if not requirements:
        return
    for requirement_line in requirements.split('\n'):
        if requirement_line and '==' not in requirement_line:
            return 'unfrozen_requirements', 'например, %s' % requirement_line
```

Specifically, if add `requirements.txt` fixture with no frozen requirement to test_repo, in test we can catch only condition ` if requirement_line and '==' not in requirement_line:`.
Respectively, if we don't add `requirements.txt` - we catch `if not requirements:` only.
What is the best solution to the testing 2 conditions (not file and not frozen requirement)?

**Comment by patrnk** [comment]
OK, this is actually the case we will have to account for in the future. But for now, you can test the first case in `general_repo` and the second one in `general_repo_original`.

Make sure this arrangement doesn't break the existing tests.

**Comment by patrnk** [comment]
The coverage now is 90%+. I think we can close the issue now.
