### ISSUE TITLE
Problem with are_sources_in_utf validator 

### ISSUE THREAD

**Issue by Askanio234** [devmanorg/fiasko_bro#64]
https://github.com/devmanorg/fiasko_bro/blob/2166a85129ee19a249dff025de822b18c2205248/fiasko_bro/repository_info.py#L22

Since we instantiating LocalRepositoryInfo object before any validators, a repo with different encoding (tested with win-1251) will raise an exception during instantiating in this function. Due to this, the above-mentioned validator will not be called at all. Please advise further course of action.

**Comment by Askanio234** [comment]
One option is to not to declare encoding explicitly in with open() and rewrite validator to actively indentify encoding via may be some libs like python-magic.

**Comment by Melevir** [comment]
Nice bug, thanks for the report. 
I guess we need validators pack, that runs before LocalRepositoryInfo created. We should move there validators are_sources_in_utf and is_repo_too_large for now.
@Askanio234 can you make pull request today or tomorrow?

**Comment by Askanio234** [comment]
@Melevir Yes i will do it today, i think same goes to syntax error validator.
