### ISSUE TITLE
False positive on compare_response_status_to_200

### ISSUE THREAD

**Issue by Askanio234** [devmanorg/fiasko_bro#67]
While working on another issue i use this project of mine for testing [link](https://github.com/Askanio234/Tanks/blob/master/Tanks.py) in the validate_repo() results i noticed ('compare_response_status_to_200', '') error tuple which i think is not working as designed because my project does not involve any HTTP status codes at all.

**Comment by Melevir** [comment]
Provide short snippet to validate the issue, please.

**Comment by Askanio234** [comment]
Behavior is no longer observed after PR #70 Good job @patrnk! Issue can be closed.
