### ISSUE TITLE
Question: are you checking module and package names?

### ISSUE THREAD

**Issue by sobolevn** [devmanorg/fiasko_bro#71]
Sorry, I might have missed either are you checking module or package names or not.

Just to make it clear: package and module names should be all lowercase with `_` as possible separator. It is also wise to check maximum length of names.

There's a plugin for `flake8` for this: https://pypi.python.org/pypi/flake8-module-name/0.1.5

Here's a usage example: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/Pipfile#L26

P.S. You have almost completely reinvented all possible `flake8` plugins.
P.S.S. I am obsessed with code quality and coding styling, so I am going to steal some rules from you and make it as a separate `flake8` plugins.

**Comment by patrnk** [comment]
It turns out, we do not check the module/package names at all. Thanks for pointing that out!

**Comment by Melevir** [comment]
The validator will be added in #72
