### ISSUE TITLE
Fix has_no_bom validator

### ISSUE THREAD

**Issue by Melevir** [devmanorg/fiasko_bro#86]
Now it uses get_ast_trees method and thats an error: ast tree generation fails for files with BOM.

**Comment by Askanio234** [comment]
Possible solution would be to move bom validator to prevalidators and do not use .get_ast_trees?

**Comment by patrnk** [comment]
How come [current tests](https://github.com/devmanorg/fiasko_bro/blob/master/tests/test_encoding_validators/test_has_no_BOM.py) don't catch that?

See, for example, [build 144](https://travis-ci.org/devmanorg/fiasko_bro/builds/347384534?utm_source=github_status&utm_medium=notification).
